apiVersion: xjoin.cloud.redhat.com/v1alpha1
kind: XJoinPipeline
metadata:
  name: xjoinpipeline-sample
spec:
  connectCluster: connect
  connectClusterNamespace: test
  kafkaCluster: kafka
  kafkaClusterNamespace: test
  managedKafka: false
  managedKafkaSecretName: ephem-managed-kafka
  managedKafkaSecretNamespace: test
  pause: false
