apiVersion: xjoin.cloud.redhat.com/v1alpha1
kind: XJoinDataSource
metadata:
  name: test
spec:
  pause: false
  databaseHostname:
    valueFrom:
      secretKeyRef:
        name: host-inventory-db
        key: hostname
  databasePort:
    valueFrom:
      secretKeyRef:
        name: host-inventory-db
        key: port
  databaseUsername:
    valueFrom:
      secretKeyRef:
        name: host-inventory-db
        key: username
  databasePassword:
    valueFrom:
      secretKeyRef:
        name: host-inventory-db
        key: password
  databaseName:
    valueFrom:
      secretKeyRef:
        name: host-inventory-db
        key: name
  databaseTable:
    value: "public.hosts"
  avroSchema: >
    {
      "type": "record",
      "fields": [
        {
          "name": "id",
          "type": {
            "type": "string",
            "connect.version": 1,
            "connect.name": "io.debezium.data.Uuid",
            "xjoin.type": "string"
          }
        },
        {
          "name": "account",
          "type": {
            "type": "string",
            "xjoin.type": "string"
          }
        },
        {
          "name": "display_name",
          "type": [
            "null",
            {
              "type": "string",
              "xjoin.type": "string",
              "xjoin.case": "insensitive"
            }
          ],
          "default": null
        },
        {
          "name": "created_on",
          "type": {
            "type": "string",
            "connect.version": 1,
            "connect.name": "io.debezium.time.ZonedTimestamp",
            "xjoin.type": "date_nanos"
          }
        },
        {
          "name": "modified_on",
          "type": {
            "type": "string",
            "connect.version": 1,
            "connect.name": "io.debezium.time.ZonedTimestamp",
            "xjoin.type": "date_nanos"
          }
        },
        {
          "name": "facts",
          "type": [
            "null",
            {
              "type": "string",
              "connect.version": 1,
              "connect.name": "io.debezium.data.Json",
              "xjoin.type": "json"
            }],
          "default": null
        },
        {
          "name": "tags",
          "type": [
            "null",
            {
              "type": "string",
              "connect.version": 1,
              "connect.name": "io.debezium.data.Json",
              "xjoin.type": "json"
            }],
          "default": null
        },
        {
          "name": "canonical_facts",
          "type": {
            "type": "string",
            "connect.version": 1,
            "connect.name": "io.debezium.data.Json",
            "xjoin.type": "json",
            "xjoin.fields": [
              {
                "name": "fqdn",
                "type": {
                  "xjoin.type": "string",
                  "xjoin.case": "insensitive"
                }
              },
              {
                "name": "insights_id",
                "type": {
                  "xjoin.type": "string"
                }
              },
              {
                "name": "satellite_id",
                "type": {
                  "xjoin.type": "string"
                }
              }
            ]
          }
        },
        {
          "name": "system_profile_facts",
          "type": [
            "null",
            {
              "type": "string",
              "connect.version": 1,
              "connect.name": "io.debezium.data.Json",
              "xjoin.type": "json",
              "xjoin.fields": [
                {
                  "name": "arch",
                  "type": {
                    "xjoin.type": "string"
                  }
                },
                {
                  "name": "os_release",
                  "type": {
                    "xjoin.type": "string"
                  }
                },
                {
                  "name": "os_kernel_version",
                  "type": {
                    "xjoin.type": "string"
                  }
                },
                {
                  "name": "infrastructure_type",
                  "type": {
                    "xjoin.type": "string"
                  }
                },
                {
                  "name": "infrastructure_vendor",
                  "type": {
                    "xjoin.type": "string"
                  }
                },
                {
                  "name": "sap_system",
                  "type": {
                    "xjoin.type": "boolean"
                  }
                },
                {
                  "name": "sap_sids",
                  "type": {
                    "xjoin.type": "string"
                  }
                },
                {
                  "name": "owner_id",
                  "type": {
                    "xjoin.type": "string"
                  }
                },
                {
                  "name": "insights_client_version",
                  "type": {
                    "xjoin.type": "string"
                  }
                },
                {
                  "name": "rhc_client_id",
                  "type": {
                    "xjoin.type": "string"
                  }
                },
                {
                  "name": "is_marketplace",
                  "type": {
                    "xjoin.type": "boolean"
                  }
                },
                {
                  "name": "operating_system",
                  "type": {
                    "xjoin.type": "json",
                    "xjoin.fields": [
                      {
                        "name": "major",
                        "type": {
                          "xjoin.type": "byte"
                        }
                      },
                      {
                        "name": "minor",
                        "type": {
                          "xjoin.type": "byte"
                        }
                      },
                      {
                        "name": "name",
                        "type": {
                          "xjoin.type": "string"
                        }
                      }
                    ]
                  }
                },
                {
                  "name": "ansible",
                  "type": {
                    "xjoin.type": "json",
                    "xjoin.fields": [
                      {
                        "name": "controller_version",
                        "type": {
                          "xjoin.type": "string"
                        }
                      },
                      {
                        "name": "hub_version",
                        "type": {
                          "xjoin.type": "string"
                        }
                      },
                      {
                        "name": "catalog_worker_version",
                        "type": {
                          "xjoin.type": "string"
                        }
                      },
                      {
                        "name": "sso_version",
                        "type": {
                          "xjoin.type": "string"
                        }
                      }
                    ]
                  }
                },
                {
                  "name": "host_type",
                  "type": {
                    "xjoin.type": "string"
                  }
                }
              ]
          }],
          "default": null
        },
        {
          "name": "ansible_host",
          "type": [
            "null",
            {
              "type": "string",
              "xjoin.type": "string"
            }],
          "default": null
        },
        {
          "name": "stale_timestamp",
          "type": {
            "type": "string",
            "xjoin.type": "date_nanos",
            "connect.version": 1,
            "connect.name": "io.debezium.time.ZonedTimestamp"
          }
        },
        {
          "name": "reporter",
          "type": {
            "type": "string",
            "xjoin.type": "string"
          }
        },
        {
          "name": "per_reporter_staleness",
          "xjoin.index": false,
          "type": {
            "type": "string",
            "connect.version": 1,
            "connect.name": "io.debezium.data.Json",
            "xjoin.type": "json"
          }
        }
      ]
    }