apiVersion: v1
data:
  standard.interval: '120'
  validation.interval: '5'
  validation.attempts.threshold: '3'
  validation.percentage.threshold: '5'
  init.validation.interval: '10'
  init.validation.attempts.threshold: '10'
  init.validation.percentage.threshold: '5'
  connect.cluster: xjoin-kafka-connect-strimzi
  connector.tasks.max: '1'
kind: ConfigMap
metadata:
  name: xjoin
